docs/i18n.md

Changed 'localiation' to 'localization'

Fixed spelling error in localization doc

---

lorien/InfiniteCanvas/InfiniteCanvas.gd
lorien/Main.gd

This should fix the crash from issue #35
For some reason, Lorien Crashes when the viewport object becomes smaller than 4 pixels. This check for that and prevents the change.

Fixing Crash from Issue #35

---

lorien/Assets/I18n/de.txt
lorien/Assets/I18n/en.txt
lorien/Assets/I18n/es.txt
lorien/Assets/I18n/it.txt
lorien/Assets/I18n/ru.txt
lorien/UI/Dialogs/SettingsDialog.tscn

I wanted to add a new setting to the settings dialog and noticed that some translation keys were named inconsistently. I also found some missing ones (except German and English), so i added them to the other translations in English with a TODO comment. It's probably easier to keep track what still lacks translations when we do it like that.

Cleanup translations

---

lorien/InfiniteCanvas/Tools/LineTool.gd

Let me know if this is the right approach. I think it's a good trade-off between usability and performance/small savefiles.
Fixes #59

Subdivide line strokes so that they are easier to select

---

lorien/Main.tscn
lorien/UI/Toolbar.gd

fixes issue #99
It seems this is bug is caused the popup nodes functionality, See line 148 https://github.com/godotengine/godot/blob/master/scene/gui/popup.cpp
So an alternative would be to use a different type of node and handle the closing input events like the palette button
In this implementation I could group the Menubar and Toolbar into a VBox and then use the size.y of the VBox instead of the assumption at line 155
line 158-160 makes the background color picker move with the window when its resized. Which is a workaround for a bug in godot https://github.com/godotengine/godot/issues/38171

Background color picker bug

---

lorien/UI/Themes/theme_dark.tres

Fixes #104
Adds a new style to the theme to stop from covering FileDialog's file tree when in focus.
This solution adds a blended border at the bottom of the file tree when its in focus, an alternative would be to get rid of the style entirely.

Add style to dark theme to make FileDialog's file tree visible 

---

docs/changelog.md
lorien/project.godot

A simple (and temporary?) solution to #114.  Simply separates the single key combo `CTRL + CMD + KEY` into two separate key combos `CTRL + KEY` and `CMD + KEY`. Only down side is that on Mac, you'll be able to do all actions via both `CTRL` and `CMD` instead of *just* `CMD`.

Update keyboard shortcuts for MacOS

---

lorien/Assets/I18n/zh-CN.txt

1. The font name of Simplified Chinese can' t be displayed properly in other languages, for example, when the language is set to English, it will be displayed as blank, so I changed it from "简体中文" to "Simplified Chinese". For your convenience, you can view the following screenshots.
3. Improved the translation of Simplified Chinese.

Improve Simplified Chinese translation

---

README.md

The readme linked to an older version of the manual, this tiny commit fixes that and re-worded it a bit so it's more obvious where that link takes you.

Update manual link in README to v0.5 (was v0.4)

---

lorien/UI/Dialogs/EditPaletteDialog.gd

Not a major change; just uses the last selected color for the new color when creating a palette.
In most programs (even ms paint), when adding a color to a palette it doesn't reset the color to white. Instead, it keeps the selected color.
See GIF of changes:
.

Maintain selected color when adding to palette

---

lorien/Misc/Settings.gd
lorien/UI/Dialogs/KeyBindingsList.gd

Requires #169 and #159 to be merged first.
https://user-images.githubusercontent.com/542105/176624429-7285d72c-5e66-4af7-9298-e34102bfcd68.mp4
Changes:
- I refactored PR #159 of @HuntClauss a bit. Simplified it and gave it some "forwards compatibility" that might otherwise be annoying to user (see code comment).
- Added `store_shortcuts()` function to Settings which is called to persist keybindings

Keybindings persistence

---

lorien/Assets/I18n/en.txt
lorien/InfiniteCanvas/Cursor/BaseCursor.gd
lorien/InfiniteCanvas/InfiniteCanvas.gd
lorien/InfiniteCanvas/PanZoomCamera.gd
lorien/InfiniteCanvas/Tools/BrushTool.gd
lorien/InfiniteCanvas/Tools/CanvasTool.gd
lorien/InfiniteCanvas/Tools/CircleTool.gd
lorien/InfiniteCanvas/Tools/EraserTool.gd
lorien/InfiniteCanvas/Tools/LineTool.gd
lorien/InfiniteCanvas/Tools/RectangleTool.gd
lorien/InfiniteCanvas/Tools/SelectionTool.gd
lorien/project.godot

This is the one that I really was interested in (especially the zoom).
Maybe also addresses: #147 (?)
https://user-images.githubusercontent.com/542105/177951522-daef7bbb-9e5e-41f6-8d3e-03eb4dd07db8.mp4
- Adds keybinding actions for panning the canvas and zooming. Default keybindings: Arrow keys and +/- for zooming
- Refactored the way cursors update their position, making the cursors themselves responsible for updating their location. Removed cursor position updates from all tools.
- Had to be done, because panning was causing the cursor location to shift and adding the fix to that to all tools seemed like an extreme amount of code duplication.

Canvas keybinding controls

---

lorien/UI/Dialogs/KeyBindingsList.gd

Fixed by checking if a child node has a signal before attempting to binding to it.
Sorry, this went awry during a cleanup of one of my earlier PRs where I deleted unused signals.
Fixes #178

Fix errors mentionied in issue #178

---

lorien/UI/Dialogs/KeyBindingsList.gd

Sorts the keybindings by their translated string.
Fixes #179

Sort keybindings by translated name

---

docs/changelog.md
lorien/Main.gd
lorien/UI/Dialogs/SettingsDialog.gd

Calculate UI auto scaling based on platform for more accurate scaling. Also wider range of allowed UI scales for some displays.
The scaling for Linux could probably be improved further, but will be much easier if Godot implements better scaling/dpi support in the engine itself.

Platform UI scaling

---

public/linux/com.github.mbrlabs.Lorien.desktop
public/linux/com.github.mbrlabs.Lorien.metainfo.xml
public/linux/com.github.mbrlabs.Lorien.mimetype.xml
public/linux/x-lorien-canvas.mimetype.xml

This PR adds metadata files required for packaging on Linux, for example Flatpak. See https://github.com/mbrlabs/Lorien/issues/17.
The files are currently stored in [tinywrkb's Flatpak repo](https://github.com/tinywrkb/flathub/tree/com.github.mbrlabs.Lorien) but it is recommended to have the files in the upstream repository so they are the same for all packages and can easily be modified by the upstream author.

Add Linux metadata files

---

lorien/InfiniteCanvas/Tools/SelectionTool.gd

Fixes missing on-canvas cursor when switching to SelectionTool for the first time.
Fixes bug introduced by: bc83fbe6691c (`Reset state of tool being switched (#155)`)

SelectionTool: fix missing cursor on initial usage

---

lorien/InfiniteCanvas/Tools/BrushTool.gd

Two changes:
1. The tool_event InputEvent is either a MouseMotion or a MouseButton, so the check for the InputEvent being a MouseButton event does not need to occur if the object is already identified as a MouseMotion.
2. In the tool_event MouseButton path, if the elif section is reached then event.pressed is guaranteed to be false, so checking that it is false is redundant.

Minor changes to remove checks for logically impossible situations

---

lorien/InfiniteCanvas/InfiniteCanvas.gd
lorien/Misc/Types.gd

Related: #118
For tablet pens with an eraser, the eraser tool is set active when the eraser side of the pen is used.
Originally active tool is re-activated once the pen is non-inverted.

InfiniteCanvas: Use eraser tool while tablet pen is inverted

---

lorien/Assets/I18n/en.txt
lorien/Config.gd
lorien/InfiniteCanvas/Tools/CircleTool.gd
lorien/InfiniteCanvas/Tools/LineTool.gd
lorien/InfiniteCanvas/Tools/RectangleTool.gd
lorien/Misc/Settings.gd
lorien/UI/Dialogs/SettingsDialog.gd
lorien/UI/Dialogs/SettingsDialog.tscn

- Added configuration to Settings Dialog
- Circle, Line and Rectangle Tool pressure use the configured pressure instead of the constant 0.5
Should fix #212, #252 and #216

Added Default Tools Pressure setting.

---

docs/contributing.md

Since Lorien uses event.pen_inverted, version 3.4.4 is not working anymore.

Updated Godot version to use in contribution guide

---

lorien/InfiniteCanvas/PanZoomCamera.gd

When I was playing with this program and reading the code, I found a peculiar issue. When I drew a dot on the canvas and the mouse hovered over the dot, after many zoom-in and zoom-out operations, the dot would gradually deviate from the mouse. So I re-derived the formula myself and solved the problem, just need to change one line of code.

Fix formula of keep content fixed under the cursor

---

lorien/Main.gd
lorien/ProjectManager/Project.gd
lorien/ProjectManager/ProjectManager.gd
lorien/UI/Components/FlatTextureButton.gd
lorien/UI/Toolbar.gd

Second take. (First take: #256)
I've rewritten it from scratch for the new Godot 4 version. I think my new approach looks much cleaner; let me know if anything needs to be changed.
I've tested it and it works as expected when switching between tabs, adding tabs, closing tabs, and loading projects. And this time the undo/redo buttons don't react when you zoom in/out, although, zooming still incorrectly dirties the project as mentioned in my previous PR.

Disable undo/redo buttons when there is nothing to undo/redo

---

lorien/Assets/I18n/en.txt
lorien/InfiniteCanvas/PanZoomCamera.gd
lorien/project.godot

As suggested in the issues #238 and #226, I have added a new input "canvas_pan_key" which allows to pan the viewport the same as the middle mouse button does. 
New input is defaulted to control + space, because I don't want to change the default behavior of the application. But everyone who needs it can configure it to the space bar and replace the "center to mouse position".

Pan with space or any other key

---

.gitignore
lorien/InfiniteCanvas/InfiniteCanvas.gd
lorien/InfiniteCanvas/PanZoomCamera.gd
lorien/InfiniteCanvas/Tools/BrushTool.gd
lorien/InfiniteCanvas/Tools/CanvasTool.gd
lorien/InfiniteCanvas/Tools/CircleTool.gd
lorien/InfiniteCanvas/Tools/EraserTool.gd
lorien/InfiniteCanvas/Tools/LineTool.gd
lorien/InfiniteCanvas/Tools/RectangleTool.gd
lorien/InfiniteCanvas/Tools/SelectionTool.gd

Closes #301 .
Branched off main. Tested in debug and Windows release export.
**Notable changes and explanation of new behaviour:**
- While panning or zooming drawing will no longer be possible.
- The brush tool has a special behaviour: when starting to draw with the brush, then starting to zoom, the brush stroke is ended.
- No matter the tool, if you start drawing and then pan while drawing, you can continue drawing smoothly from where you left off once you stop panning.
- Except for the brush tool, geometric shapes can be adjusted while zooming after they have been initiated.
**Observed bugs:**
- For some reason my graphic tablet's pen movement is not recognized. That seems to be an issue with the main branch though and was not introduced by me.
- Sometimes, while drawing, panning and or …

Disable stroke while panning or zooming

---

lorien/Config.gd
lorien/Main.gd

This lowers the FPS based on if there was user input the last 250ms. It significantly reduces GPU/CPU load when the user is idle.
Fixes #305

Adaptive FPS

---

lorien/Assets/I18n/ar.txt
lorien/Assets/I18n/de.txt
lorien/Assets/I18n/en.txt
lorien/Assets/I18n/es.txt
lorien/Assets/I18n/fr.txt
lorien/Assets/I18n/it.txt
lorien/Assets/I18n/ko.txt
lorien/Assets/I18n/pt-BR.txt
lorien/Assets/I18n/ru.txt
lorien/Assets/I18n/tr.txt
lorien/Assets/I18n/uk.txt
lorien/Assets/I18n/zh-CN.txt
lorien/Assets/I18n/zh-TW.txt
lorien/Main.gd
lorien/Misc/Settings.gd
lorien/UI/Dialogs/SettingsDialog.gd
lorien/UI/Dialogs/SettingsDialog.tscn
lorien/project.godot

This seems to fix an issue for at least some Wacom tablets on Windows as discussed in #303.

Added tablet driver settings and made wintab default on Windows

---

lorien/InfiniteCanvas/Cursor/SelectionCursor/SelectionCursor.gd

Small fix where the selection cursor was scaling wrong causing the cursor to be invisible at small zoom and be too large on high zoom

Fixed selection cursor zoom

---

lorien/InfiniteCanvas/Tools/EraserTool.gd

This should fix the issue mentioned here: #321 
The existing solution was only checking, if the stroke intersects with the circle of the eraser. I have added a logic that checks if a point is inside the circle.

Fix for Eraser issue, with too big eraser radius

---

lorien/InfiniteCanvas/PanZoomCamera.gd
lorien/project.godot

Same as #227 but ported for Godot 4
---
I noticed the zooming and panning is not smooth, but very jagged, when using my fingers on my 2-in-1. 
Does someone know what might be causing this issue?

Godot 4: Touch screen pans and zooms on canvas by using drag and pinch
